apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: mirjahal
        repo: gitops-argocd
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: stack-apps-{{branch_slug}}-{{number}}
    spec:
      project: "default"
      source:
        repoURL: https://github.com/mirjahal/gitops-argocd.git
        targetRevision: '{{head_sha}}'
        path: day-2/
      destination:
        server: https://kubernetes.default.svc
        namespace: 'day-2-app-of-apps-{{branch_slug}}-{{number}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true